# Generated by Django 5.1.7 on 2025-10-07 13:38

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRules',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scope_entity', models.CharField(choices=[('provider', 'Provider'), ('product', 'Product'), ('module', 'Module'), ('coverage', 'Coverage'), ('parameter', 'Parameter')], max_length=20)),
                ('scope_id', models.IntegerField()),
                ('rule_type', models.CharField(choices=[('eligibility', 'Eligibility Rule'), ('validation', 'Validation Rule'), ('calculation', 'Calculation Rule'), ('exclusion', 'Exclusion Rule'), ('dependency', 'Dependency Rule')], max_length=20)),
                ('condition_json', models.JSONField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Business Rules',
                'db_table': 'business_rules',
            },
        ),
        migrations.CreateModel(
            name='DekkingsItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Dekkings Items',
                'db_table': 'dekkings_items',
            },
        ),
        migrations.CreateModel(
            name='DekkingsNiveaus',
            fields=[
                ('niveau_id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau_name', models.CharField(max_length=255)),
                ('niveau_rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Dekkings Niveaus',
                'db_table': 'dekkings_niveaus',
                'ordering': ['niveau_rank'],
            },
        ),
        migrations.CreateModel(
            name='Doelgroepen',
            fields=[
                ('doelgroep_id', models.AutoField(primary_key=True, serialize=False)),
                ('doelgroep_naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Doelgroepen',
                'db_table': 'doelgroepen',
            },
        ),
        migrations.CreateModel(
            name='Landen',
            fields=[
                ('land_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('land_naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Landen',
                'db_table': 'landen',
            },
        ),
        migrations.CreateModel(
            name='ParameterOpties',
            fields=[
                ('optie_id', models.AutoField(primary_key=True, serialize=False)),
                ('optie_waarde_tekst', models.CharField(max_length=255)),
                ('min_waarde', models.IntegerField(blank=True, null=True)),
                ('max_waarde', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Parameter Opties',
                'db_table': 'parameter_opties',
            },
        ),
        migrations.CreateModel(
            name='PremieParameters',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_naam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Premie Parameters',
                'db_table': 'premie_parameters',
            },
        ),
        migrations.CreateModel(
            name='Producten',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('beschrijving', models.TextField(blank=True)),
                ('policy_type', models.CharField(choices=[('flexible', 'Flexible'), ('individual', 'Individual'), ('family', 'Family'), ('group', 'Group'), ('corporate', 'Corporate')], max_length=20)),
                ('max_leeftijd_aanvraag', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('max_leeftijd_dekking', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
            ],
            options={
                'verbose_name_plural': 'Producten',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Verzekeraars',
            fields=[
                ('verzekeraar_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('contact_details', models.JSONField(default=dict)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Verzekeraars',
                'db_table': 'verzekeraars',
            },
        ),
        migrations.CreateModel(
            name='DekkingsCategorien',
            fields=[
                ('categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie_naam', models.CharField(max_length=255)),
                ('parent_categorie_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='comparator_app.dekkingscategorien')),
            ],
            options={
                'verbose_name_plural': 'Dekkings Categorien',
                'db_table': 'dekkings_categorien',
            },
        ),
        migrations.CreateModel(
            name='ItemCategorieMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.dekkingscategorien')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.dekkingsitems')),
            ],
            options={
                'verbose_name_plural': 'Item Category Mappings',
                'db_table': 'item_category_mapping',
                'unique_together': {('item_id', 'categorie_id')},
            },
        ),
        migrations.AddField(
            model_name='dekkingsitems',
            name='categorien',
            field=models.ManyToManyField(related_name='dekkings_items', through='comparator_app.ItemCategorieMapping', to='comparator_app.dekkingscategorien'),
        ),
        migrations.CreateModel(
            name='Klanten',
            fields=[
                ('klant_id', models.AutoField(primary_key=True, serialize=False)),
                ('emailadres', models.EmailField(max_length=254, unique=True)),
                ('voorletters', models.CharField(max_length=10)),
                ('achternaam', models.CharField(max_length=255)),
                ('geboortedatum', models.DateField()),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('nationaliteit_land_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nationals', to='comparator_app.landen')),
            ],
            options={
                'verbose_name_plural': 'Klanten',
                'db_table': 'klanten',
            },
        ),
        migrations.CreateModel(
            name='Aanvragen',
            fields=[
                ('aanvraag_id', models.AutoField(primary_key=True, serialize=False)),
                ('vertrekdatum', models.DateField()),
                ('ingediend_op', models.DateTimeField(auto_now_add=True)),
                ('klant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aanvragen', to='comparator_app.klanten')),
                ('bestemmings_land_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aanvragen_bestemming', to='comparator_app.landen')),
            ],
            options={
                'verbose_name_plural': 'Aanvragen',
                'db_table': 'aanvragen',
            },
        ),
        migrations.CreateModel(
            name='Polissen',
            fields=[
                ('polis_id', models.AutoField(primary_key=True, serialize=False)),
                ('polisnummer', models.CharField(max_length=255, unique=True)),
                ('startdatum', models.DateField()),
                ('totale_premie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('klant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polissen', to='comparator_app.klanten')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polissen', to='comparator_app.producten')),
            ],
            options={
                'verbose_name_plural': 'Polissen',
                'db_table': 'polissen',
            },
        ),
        migrations.CreateModel(
            name='PolisOpties',
            fields=[
                ('polis_optie_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polis_opties', to='comparator_app.parameteropties')),
                ('polis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polis_opties', to='comparator_app.polissen')),
            ],
            options={
                'verbose_name_plural': 'Polis Opties',
                'db_table': 'polis_opties',
            },
        ),
        migrations.CreateModel(
            name='PremieParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.parameteropties')),
            ],
            options={
                'verbose_name_plural': 'Premie Parameter Mappings',
                'db_table': 'premie_parameter_mapping',
            },
        ),
        migrations.AddField(
            model_name='parameteropties',
            name='parameter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opties', to='comparator_app.premieparameters'),
        ),
        migrations.CreateModel(
            name='Premies',
            fields=[
                ('premie_id', models.AutoField(primary_key=True, serialize=False)),
                ('premie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('termijn', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premies', to='comparator_app.dekkingsniveaus')),
                ('parameter_opties', models.ManyToManyField(related_name='premies', through='comparator_app.PremieParameterMapping', to='comparator_app.parameteropties')),
            ],
            options={
                'verbose_name_plural': 'Premies',
                'db_table': 'premies',
            },
        ),
        migrations.AddField(
            model_name='premieparametermapping',
            name='premie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.premies'),
        ),
        migrations.CreateModel(
            name='ProductModules',
            fields=[
                ('product_module_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_verplicht', models.BooleanField(default=False)),
                ('module_naam', models.CharField(blank=True, max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modules', to='comparator_app.producten')),
            ],
            options={
                'verbose_name_plural': 'Product Modules',
                'db_table': 'product_modules',
            },
        ),
        migrations.AddField(
            model_name='premies',
            name='product_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premies', to='comparator_app.productmodules'),
        ),
        migrations.AddField(
            model_name='premieparameters',
            name='product_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premie_parameters', to='comparator_app.productmodules'),
        ),
        migrations.CreateModel(
            name='PolisModules',
            fields=[
                ('polis_module_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polis_modules', to='comparator_app.dekkingsniveaus')),
                ('polis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polis_modules', to='comparator_app.polissen')),
                ('product_module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polis_modules', to='comparator_app.productmodules')),
            ],
            options={
                'verbose_name_plural': 'Polis Modules',
                'db_table': 'polis_modules',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('metadata', models.JSONField(default=dict)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='comparator_app.producten')),
                ('product_module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='comparator_app.productmodules')),
            ],
            options={
                'verbose_name_plural': 'Document Chunks',
                'db_table': 'document_chunk',
            },
        ),
        migrations.CreateModel(
            name='ProductTargetDoelgroepen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doelgroep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.doelgroepen')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.producten')),
            ],
            options={
                'verbose_name_plural': 'Product Target Doelgroepen',
                'db_table': 'product_target_doelgroepen',
                'unique_together': {('product_id', 'doelgroep_id')},
            },
        ),
        migrations.AddField(
            model_name='producten',
            name='target_doelgroepen',
            field=models.ManyToManyField(related_name='products', through='comparator_app.ProductTargetDoelgroepen', to='comparator_app.doelgroepen'),
        ),
        migrations.CreateModel(
            name='VerzekeraarRegio',
            fields=[
                ('verzekeraar_regio_id', models.AutoField(primary_key=True, serialize=False)),
                ('regio_naam', models.CharField(max_length=255)),
                ('verzekeraar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regios', to='comparator_app.verzekeraars')),
            ],
            options={
                'verbose_name_plural': 'Verzekeraar Regio',
                'db_table': 'verzekeraar_regio',
            },
        ),
        migrations.AddField(
            model_name='producten',
            name='verzekeraar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='comparator_app.verzekeraars'),
        ),
        migrations.AlterUniqueTogether(
            name='premieparametermapping',
            unique_together={('premie_id', 'optie_id')},
        ),
        migrations.AlterUniqueTogether(
            name='premieparameters',
            unique_together={('product_module_id', 'parameter_naam')},
        ),
        migrations.CreateModel(
            name='DekkingsItemDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('dekkings_type', models.CharField(choices=[('amount', 'Fixed Amount'), ('percentage', 'Percentage'), ('limit', 'Coverage Limit'), ('deductible', 'Deductible'), ('excluded', 'Excluded'), ('included', 'Included')], max_length=20)),
                ('numerieke_waarde', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('periode', models.CharField(blank=True, max_length=50)),
                ('voorwaarden_tekst', models.TextField(blank=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dekking_details', to='comparator_app.dekkingsitems')),
                ('niveau_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dekking_details', to='comparator_app.dekkingsniveaus')),
                ('product_module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dekking_details', to='comparator_app.productmodules')),
            ],
            options={
                'verbose_name_plural': 'Dekkings Item Details',
                'db_table': 'dekkings_item_details',
                'unique_together': {('niveau_id', 'item_id', 'product_module_id')},
            },
        ),
        migrations.CreateModel(
            name='VerzekeraarRegioLanden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.landen')),
                ('verzekeraar_regio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.verzekeraarregio')),
            ],
            options={
                'verbose_name_plural': 'Verzekeraar Regio Landen',
                'db_table': 'verzekeraar_regio_landen',
                'unique_together': {('verzekeraar_regio_id', 'land_code')},
            },
        ),
    ]
