# Generated by Django 5.1.7 on 2026-01-08 15:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRules',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scope_entity', models.CharField(choices=[('provider', 'Provider'), ('product', 'Product'), ('module', 'Module'), ('coverage', 'Coverage'), ('parameter', 'Parameter')], max_length=20)),
                ('scope_id', models.IntegerField()),
                ('rule_type', models.CharField(choices=[('eligibility', 'Eligibility Rule'), ('validation', 'Validation Rule'), ('calculation', 'Calculation Rule'), ('exclusion', 'Exclusion Rule'), ('dependency', 'Dependency Rule')], max_length=20)),
                ('condition_json', models.JSONField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Business Rules',
                'db_table': 'business_rules',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('policy_type', models.CharField(choices=[('flexible', 'Flexible'), ('individual', 'Individual'), ('family', 'Family'), ('group', 'Group'), ('corporate', 'Corporate')], max_length=20)),
                ('max_age_application', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('max_age_coverage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Relaties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatie_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('ts_aangemaakt', models.DateTimeField(blank=True, null=True)),
                ('hoofdnaam', models.CharField(blank=True, max_length=255, null=True)),
                ('email_adressen', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('api', 'Assuportal API'), ('adviesaanvraag', 'Advies Aanvraag')], default='api', max_length=20)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Relaties',
                'db_table': 'relaties',
            },
        ),
        migrations.CreateModel(
            name='TargetAudiences',
            fields=[
                ('audience_id', models.AutoField(primary_key=True, serialize=False)),
                ('audience_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Target Audiences',
                'db_table': 'target_audiences',
            },
        ),
        migrations.CreateModel(
            name='ProductModules',
            fields=[
                ('product_module_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('provider_specific_name', models.CharField(blank=True, max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modules', to='comparator_app.products')),
            ],
            options={
                'verbose_name_plural': 'Product Modules',
                'db_table': 'product_modules',
            },
        ),
        migrations.CreateModel(
            name='ProviderRegions',
            fields=[
                ('provider_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='comparator_app.providers')),
            ],
            options={
                'verbose_name_plural': 'Provider Regions',
                'db_table': 'provider_regions',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='comparator_app.providers'),
        ),
        migrations.CreateModel(
            name='Personen',
            fields=[
                ('persoon_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_persoon_id', models.IntegerField(blank=True, null=True)),
                ('persoon_naam', models.CharField(max_length=255)),
                ('persoon_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personen', to='comparator_app.relaties')),
            ],
            options={
                'verbose_name_plural': 'Personen',
                'db_table': 'personen',
            },
        ),
        migrations.CreateModel(
            name='Contracten',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('polisnummer', models.CharField(max_length=255, unique=True)),
                ('branche', models.CharField(blank=True, max_length=255, null=True)),
                ('datum_ingang', models.DateField(blank=True, null=True)),
                ('ts_aangemaakt', models.DateTimeField(blank=True, null=True)),
                ('ts_gewijzigd', models.DateTimeField(blank=True, null=True)),
                ('relatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracten', to='comparator_app.relaties')),
            ],
            options={
                'verbose_name_plural': 'Contracten',
                'db_table': 'contracten',
            },
        ),
        migrations.CreateModel(
            name='AdviesAanvragen',
            fields=[
                ('aanvraag_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_identifier', models.EmailField(max_length=254)),
                ('vertrekdatum', models.DateField()),
                ('ingediend_op', models.DateTimeField(auto_now_add=True)),
                ('bestemmings_land_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aanvragen_bestemming', to='comparator_app.countries')),
                ('relatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviesaanvragen', to='comparator_app.relaties')),
            ],
            options={
                'verbose_name_plural': 'Advies Aanvragen',
                'db_table': 'adviesaanvragen',
            },
        ),
        migrations.CreateModel(
            name='ProductTargetAudiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audience_mappings', to='comparator_app.products')),
                ('audience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_target_mappings', to='comparator_app.targetaudiences')),
            ],
            options={
                'verbose_name_plural': 'Product Target Audiences',
                'db_table': 'product_target_audiences',
                'unique_together': {('product_id', 'audience_id')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='target_audiences',
            field=models.ManyToManyField(related_name='products', through='comparator_app.ProductTargetAudiences', to='comparator_app.targetaudiences'),
        ),
        migrations.CreateModel(
            name='ProviderRegionCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_regions', to='comparator_app.countries')),
                ('provider_region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_countries', to='comparator_app.providerregions')),
            ],
            options={
                'verbose_name_plural': 'Provider Region Countries',
                'db_table': 'provider_region_countries',
                'unique_together': {('provider_region_id', 'country_code')},
            },
        ),
    ]
