# Generated by Django 5.2.6 on 2025-09-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateparametermapping',
            name='name_mapping',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='premiumrates',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='policy_type',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('individual', 'Individual'), ('family', 'Family'), ('group', 'Group'), ('corporate', 'Corporate')], max_length=20),
        ),
    ]
