# Generated by Django 5.1.7 on 2026-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracten',
            name='contract_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contracten',
            name='polisnummer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
