# Generated by Django 5.1.7 on 2025-10-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verzekeraars',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='verzekeraars',
            name='logo_url',
        ),
    ]
