# Generated by Django 5.1.7 on 2025-10-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0002_remove_verzekeraars_contact_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producten',
            name='beschrijving',
        ),
    ]
