# Generated by Django 5.2.6 on 2025-09-11 13:50

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0002_rateparametermapping_name_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateparametermapping',
            name='name_mapping',
        ),
        migrations.AlterField(
            model_name='premiumrates',
            name='level',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product_module', chained_model_field='product_module', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comparator_app.coveragelevels'),
        ),
    ]
