# Generated by Django 5.1.7 on 2025-10-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0003_remove_producten_beschrijving'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategoriemapping',
            options={'verbose_name_plural': 'Item Categorie Mappings'},
        ),
        migrations.AlterField(
            model_name='itemcategoriemapping',
            name='categorie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='comparator_app.dekkingscategorien'),
        ),
        migrations.AlterField(
            model_name='itemcategoriemapping',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_mappings', to='comparator_app.dekkingsitems'),
        ),
        migrations.AlterModelTable(
            name='itemcategoriemapping',
            table='item_categorie_mapping',
        ),
    ]
