# Generated by Django 5.2.6 on 2025-09-12 12:06

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0003_remove_rateparametermapping_name_mapping_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmodules',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coverageitems',
            name='category',
        ),
        migrations.AlterField(
            model_name='premiumrates',
            name='level',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product_module', chained_model_field='product_module', on_delete=django.db.models.deletion.CASCADE, related_name='premium_rates', to='comparator_app.coveragelevels'),
        ),
        migrations.CreateModel(
            name='ItemCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.coveragecategories')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator_app.coverageitems')),
            ],
            options={
                'verbose_name_plural': 'Item Category Mappings',
                'db_table': 'item_category_mapping',
                'unique_together': {('item', 'category')},
            },
        ),
        migrations.AddField(
            model_name='coverageitems',
            name='categories',
            field=models.ManyToManyField(related_name='coverage_items', through='comparator_app.ItemCategoryMapping', to='comparator_app.coveragecategories'),
        ),
        migrations.RemoveField(
            model_name='productmodules',
            name='module',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
