# Generated by Django 5.1.7 on 2026-01-09 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0003_adviesaanvragen_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviesaanvragen',
            name='bestemmings_land_code',
        ),
        migrations.RemoveField(
            model_name='adviesaanvragen',
            name='email_identifier',
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='aangemaakt_op',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='aanhef',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='achternaam',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='advies_voor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='advies_voor_mezelf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='advies_vorm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='andere_verzekeringen_interesse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='anders_personen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='aov_geen_offerte_reden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='bestemming_land',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='bouwplaats_hoe_vaak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='bouwplaats_of_offshore',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='bruto_jaarinkomen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='bruto_salaris_inkomen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='dekking_zwangerschap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='eerder_contact_anders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='eerder_contact_joho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='eerder_contact_keuze',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='eigen_onderneming_3jaar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='external_result_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='form_id',
            field=models.CharField(default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='functieomschrijving',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='geen_interesse_aov_reden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='geen_vaste_woonplaats',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='gevaarlijke_stoffen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='hoe_gevonden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='hoe_gevonden_overig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='hoofdreden_verblijf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='huidig_woonland',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='huidige_verzekeraar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='huis_in_nederland',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='huis_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='inkomen_toelichting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='interesse_aov',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='interesse_internationale_aov',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='interesse_zkv',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind1_geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind1_naam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind1_nationaliteit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind2_geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind2_naam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind2_nationaliteit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind3_geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind3_naam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind3_nationaliteit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind4_geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind4_naam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='kind4_nationaliteit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='land_nationaliteit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='loon_doorbetaald_bij_ziekte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='loondienst_of_zelfstandig',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='medische_bijzonderheden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='medische_bijzonderheden_toelichting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='meerdere_verzekerden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='naam_contactpersoon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='naam_werkgever',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='overlijdensrisico_bedrag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='overlijdensrisico_bedrag_anders',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='overlijdensrisico_bestemming',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='overlijdensrisico_bestemming_anders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='partner_geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='partner_naam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='partner_nationaliteit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='plannen_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='raw_form_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='referral_campaign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='referral_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='referral_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='salaris_per_maand_jaar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='salaris_uit_nederland',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='situatie_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='specifieke_wensen_zkv',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='sport_professioneel_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='sport_semiprofessioneel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='sporten_activiteiten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='telefoonnummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='toelichting_duur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='toelichting_gevaarlijke_stoffen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='toelichting_hoofdreden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='toelichting_uitkering',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='type_werkzaamheden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='uitschrijven_brp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='vaste_woonplaats',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='verwacht_inkomen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='verwachte_duur_verblijf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='voorkeur_verzekeraar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='voorletters_roepnaam',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='welke_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='wensen_toelichting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='werk_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='woning_eigen_gebruik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='woning_opmerkingen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='woning_verblijf_frequentie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='woning_verhuurd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zkv_dekkingsvariant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zkv_eigen_risico_bedrag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zkv_eigen_risico_voorkeur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zkv_geen_interesse_reden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zkv_periode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zkv_periode_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zkv_periode_omschrijving_motivatie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adviesaanvragen',
            name='zwangerschap_toelichting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='ingediend_op',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='vertrekdatum',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='relaties',
            name='aangemaakt_op',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='adviesaanvragen',
            index=models.Index(fields=['email', 'ingediend_op'], name='adviesaanvr_email_9bd2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='adviesaanvragen',
            index=models.Index(fields=['bestemming_land', 'vertrekdatum'], name='adviesaanvr_bestemm_274ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='adviesaanvragen',
            index=models.Index(fields=['interesse_zkv', 'ingediend_op'], name='adviesaanvr_interes_30e73f_idx'),
        ),
    ]
