# Generated by Django 5.1.7 on 2026-01-11 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0004_remove_adviesaanvragen_bestemmings_land_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedrijfsRegels',
            fields=[
                ('regel_id', models.AutoField(primary_key=True, serialize=False)),
                ('bereik_entiteit', models.CharField(choices=[('verzekeraar', 'Verzekeraar'), ('verzekering', 'Verzekering'), ('module', 'Module'), ('dekking', 'Dekking'), ('parameter', 'Parameter')], max_length=20)),
                ('bereik_id', models.IntegerField()),
                ('regel_type', models.CharField(choices=[('geschiktheid', 'Geschiktheidsregel'), ('validatie', 'Validatieregel'), ('berekening', 'Berekenregel'), ('uitsluiting', 'Uitsluitingsregel'), ('afhankelijkheid', 'Afhankelijkheidsregel')], max_length=20)),
                ('conditie_json', models.JSONField()),
                ('bericht', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bedrijfsregels',
                'db_table': 'bedrijfsregels',
            },
        ),
        migrations.CreateModel(
            name='VerzekeringDoelGroepen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Verzekering Doelgroepen',
                'db_table': 'verzekering_doelgroepen',
            },
        ),
        migrations.CreateModel(
            name='Verzekeringen',
            fields=[
                ('verzekering_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('omschrijving', models.TextField(blank=True)),
                ('polis_type', models.CharField(choices=[('flexibel', 'Flexibel'), ('individueel', 'Individueel'), ('gezin', 'Gezin'), ('groep', 'Groep'), ('zakelijk', 'Zakelijk')], max_length=20)),
                ('max_leeftijd_aanvraag', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('max_leeftijd_dekking', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
            ],
            options={
                'verbose_name_plural': 'Verzekeringen',
                'db_table': 'verzekeringen',
            },
        ),
        migrations.CreateModel(
            name='VerzekeringModules',
            fields=[
                ('verzekering_module_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_verplicht', models.BooleanField(default=False)),
                ('verzekeraar_specifieke_naam', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Verzekering Modules',
                'db_table': 'verzekering_modules',
            },
        ),
        migrations.CreateModel(
            name='VerzekeringRegio',
            fields=[
                ('verzekering_regio_id', models.AutoField(primary_key=True, serialize=False)),
                ('verzekeraar_naam', models.CharField(max_length=255)),
                ('regio_naam', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('actief', 'Actief'), ('inactief', 'Inactief'), ('opgeschort', 'Opgeschort')], default='actief', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Verzekering Regios',
                'db_table': 'verzekering_regio',
                'unique_together': {('verzekeraar_naam', 'regio_naam')},
            },
        ),
        migrations.CreateModel(
            name='VerzekeringRegioLanden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Verzekering Regio Landen',
                'db_table': 'verzekering_regio_landen',
            },
        ),
        migrations.DeleteModel(
            name='BusinessRules',
        ),
        # First, remove unique_together constraints before removing fields
        migrations.AlterUniqueTogether(
            name='producttargetaudiences',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='providerregioncountries',
            unique_together=set(),
        ),
        # Now remove fields
        migrations.RemoveField(
            model_name='products',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='target_audiences',
        ),
        migrations.RemoveField(
            model_name='producttargetaudiences',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='producttargetaudiences',
            name='audience_id',
        ),
        migrations.RemoveField(
            model_name='providerregioncountries',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='providerregioncountries',
            name='provider_region_id',
        ),
        migrations.RemoveField(
            model_name='providerregions',
            name='provider_id',
        ),
        # Rename models first before altering their options/fields
        migrations.RenameModel(
            old_name='TargetAudiences',
            new_name='DoelGroepen',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Landen',
        ),
        migrations.AlterModelOptions(
            name='doelgroepen',
            options={'verbose_name_plural': 'Doelgroepen'},
        ),
        migrations.AlterModelOptions(
            name='landen',
            options={'verbose_name_plural': 'Landen'},
        ),
        migrations.RenameField(
            model_name='doelgroepen',
            old_name='audience_id',
            new_name='doelgroep_id',
        ),
        migrations.RenameField(
            model_name='doelgroepen',
            old_name='audience_name',
            new_name='doelgroep_naam',
        ),
        migrations.RenameField(
            model_name='landen',
            old_name='country_code',
            new_name='land_code',
        ),
        migrations.RenameField(
            model_name='landen',
            old_name='country_name',
            new_name='land_naam',
        ),
        migrations.AlterModelTable(
            name='doelgroepen',
            table='doelgroepen',
        ),
        migrations.AlterModelTable(
            name='landen',
            table='landen',
        ),
        migrations.AddField(
            model_name='verzekeringdoelgroepen',
            name='doelgroep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verzekering_koppelingen', to='comparator_app.doelgroepen'),
        ),
        migrations.AddField(
            model_name='verzekeringen',
            name='doelgroepen',
            field=models.ManyToManyField(related_name='verzekeringen', through='comparator_app.VerzekeringDoelGroepen', to='comparator_app.doelgroepen'),
        ),
        migrations.AddField(
            model_name='verzekeringdoelgroepen',
            name='verzekering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doelgroep_koppelingen', to='comparator_app.verzekeringen'),
        ),
        migrations.AddField(
            model_name='verzekeringmodules',
            name='verzekering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verzekering_modules', to='comparator_app.verzekeringen'),
        ),
        migrations.AddField(
            model_name='verzekeringen',
            name='verzekering_regio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verzekeringen', to='comparator_app.verzekeringregio'),
        ),
        migrations.AddField(
            model_name='verzekeringregiolanden',
            name='land_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verzekering_regios', to='comparator_app.landen'),
        ),
        migrations.AddField(
            model_name='verzekeringregiolanden',
            name='verzekering_regio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regio_landen', to='comparator_app.verzekeringregio'),
        ),
        migrations.DeleteModel(
            name='ProductModules',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductTargetAudiences',
        ),
        migrations.DeleteModel(
            name='ProviderRegionCountries',
        ),
        migrations.DeleteModel(
            name='ProviderRegions',
        ),
        migrations.DeleteModel(
            name='Providers',
        ),
        migrations.AlterUniqueTogether(
            name='verzekeringdoelgroepen',
            unique_together={('verzekering', 'doelgroep')},
        ),
        migrations.AlterUniqueTogether(
            name='verzekeringregiolanden',
            unique_together={('verzekering_regio', 'land_code')},
        ),
    ]
