# Generated by Django 5.1.7 on 2025-10-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0004_alter_itemcategoriemapping_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategoriemapping',
            options={'verbose_name_plural': 'Item Category Mappings'},
        ),
        migrations.AlterField(
            model_name='itemcategoriemapping',
            name='categorie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categorie_mappings', to='comparator_app.dekkingscategorien'),
        ),
        migrations.AlterField(
            model_name='itemcategoriemapping',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categorie_mappings', to='comparator_app.dekkingsitems'),
        ),
        migrations.AlterField(
            model_name='premieparametermapping',
            name='optie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premie_mappings', to='comparator_app.parameteropties'),
        ),
        migrations.AlterField(
            model_name='premieparametermapping',
            name='premie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_mappings', to='comparator_app.premies'),
        ),
        migrations.AlterField(
            model_name='producttargetdoelgroepen',
            name='doelgroep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_target_mappings', to='comparator_app.doelgroepen'),
        ),
        migrations.AlterField(
            model_name='producttargetdoelgroepen',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_doelgroep_mappings', to='comparator_app.producten'),
        ),
        migrations.AlterField(
            model_name='verzekeraarregiolanden',
            name='land_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regio_landen', to='comparator_app.landen'),
        ),
        migrations.AlterField(
            model_name='verzekeraarregiolanden',
            name='verzekeraar_regio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regio_landen', to='comparator_app.verzekeraarregio'),
        ),
        migrations.AlterModelTable(
            name='itemcategoriemapping',
            table='item_category_mapping',
        ),
    ]
