# Generated by Django 5.2.6 on 2025-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0004_alter_productmodules_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodules',
            name='premiums_available',
            field=models.BooleanField(default=True),
        ),
    ]
