# Generated by Django 5.1.7 on 2026-01-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0005_bedrijfsregels_verzekeringdoelgroepen_verzekeringen_and_more'),
    ]

    operations = [
        # View for Verzekering Regio Landen with readable names
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE VIEW vw_verzekering_regio_landen_readable AS
                SELECT
                    vrl.id,
                    vr.verzekering_regio_id,
                    vr.verzekeraar_naam,
                    vr.regio_naam,
                    vr.verzekeraar_naam || ' - ' || vr.regio_naam AS verzekering_regio_volledige_naam,
                    vrl.land_code_id,
                    l.land_naam,
                    l.land_code,
                    vr.status
                FROM verzekering_regio_landen vrl
                JOIN verzekering_regio vr ON vrl.verzekering_regio_id = vr.verzekering_regio_id
                JOIN landen l ON vrl.land_code_id = l.land_code;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_verzekering_regio_landen_readable;"
        ),

        # View for Contracten with readable relatie info
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE VIEW vw_contracten_readable AS
                SELECT
                    c.contract_id,
                    c.polisnummer,
                    c.branche,
                    c.datum_ingang,
                    c.ts_aangemaakt,
                    c.ts_gewijzigd,
                    c.relatie_id AS relatie_database_fk_id,
                    r.relatie_id AS relatie_assuportal_id,
                    r.hoofdnaam AS relatie_naam,
                    r.ts_aangemaakt AS relatie_ts_aangemaakt,
                    r.source AS relatie_source,
                    COALESCE(r.hoofdnaam, 'Onbekend') || ' (ID: ' || COALESCE(r.relatie_id::text, 'Nieuw') || ')' AS relatie_volledige_weergave
                FROM contracten c
                JOIN relaties r ON c.relatie_id = r.id;
            """,
            reverse_sql="DROP VIEW IF EXISTS vw_contracten_readable;"
        ),
    ]
