# Generated by Django 5.2.6 on 2025-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0005_productmodules_premiums_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumrates',
            name='combination',
            field=models.CharField(default='default', help_text='Description of parameter combination', max_length=255),
        ),
    ]
