# Generated by Django 5.1.7 on 2026-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0006_add_readable_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracten',
            name='omschrijving',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
