# Generated by Django 5.1.7 on 2026-01-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator_app', '0008_remove_relaties_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='aanhef',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='achternaam',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='advies_voor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='advies_voor_mezelf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='advies_vorm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='bestemming_land',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='bouwplaats_hoe_vaak',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='bouwplaats_of_offshore',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='bruto_jaarinkomen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='bruto_salaris_inkomen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='dekking_zwangerschap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='eerder_contact_joho',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='eerder_contact_keuze',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='eigen_onderneming_3jaar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='external_result_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='functieomschrijving',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='gevaarlijke_stoffen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='hoe_gevonden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='hoofdreden_verblijf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='huidig_woonland',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='huidige_verzekeraar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='huis_in_nederland',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='huis_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='interesse_aov',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='interesse_zkv',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind1_naam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind1_nationaliteit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind2_naam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind2_nationaliteit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind3_naam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind3_nationaliteit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind4_naam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='kind4_nationaliteit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='land_nationaliteit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='loon_doorbetaald_bij_ziekte',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='loondienst_of_zelfstandig',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='medische_bijzonderheden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='meerdere_verzekerden',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='naam_contactpersoon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='naam_werkgever',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='overlijdensrisico_bedrag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='overlijdensrisico_bedrag_anders',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='partner_naam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='partner_nationaliteit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='referral_campaign',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='referral_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='salaris_per_maand_jaar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='salaris_uit_nederland',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='situatie_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='specifieke_wensen_zkv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='sport_semiprofessioneel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='telefoonnummer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='type_werkzaamheden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='uitschrijven_brp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='vaste_woonplaats',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='verwacht_inkomen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='verwachte_duur_verblijf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='voorkeur_verzekeraar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='voorletters_roepnaam',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='welke_website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='woning_eigen_gebruik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='woning_verblijf_frequentie',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='woning_verhuurd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='zkv_dekkingsvariant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='zkv_eigen_risico_bedrag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='zkv_eigen_risico_voorkeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adviesaanvragen',
            name='zkv_periode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
